### ISSUE TITLE
Getting repeated pixelFloat errors with Asclepius mod.

### ISSUE THREAD

**Issue by David-JP** [Kopernicus/Kopernicus#121]
I have been attempting to port the Asclepius mod to run with Kerbal Space Program 1.1. For the most part I have been successful but when I run the game I get the following error repeated:

[OD] ERROR: getting pixelFloatD with unloaded map Asclepius/PluginData/Asc_Height.dds of path Asclepius/PluginData/Asc_Height.dds, autoload = True

Eventually this causes the game to crash.

These are the mods I have installed:

Asclepius 1.2
Kopernicus1.0.2
MechJeb2 2.5.7.0

Attached is the log and config files.
[Asclepius.zip](https://github.com/Kopernicus/Kopernicus/files/237651/Asclepius.zip)
[output_log.zip](https://github.com/Kopernicus/Kopernicus/files/237652/output_log.zip)

**Comment by NathanKell** [comment]
Asclepius needs to correct its OnDemand settings. Not our issue, it's a cfg issue.

**Comment by ThomasKerman** [comment]
This is not an issue with the config per se but with the automated unloading of maps. Something seems to be wrong with the timer there.

**Comment by David-JP** [comment]
Is there any other information you need?

**Comment by ThomasKerman** [comment]
No, as there is no direct error, but a coding issue or an issue in Unitys C# runtime. Thanks for including output_log though :D

**Comment by ThomasKerman** [comment]
Should be fixed, monos Timer didn't work like the one from Microsoft. Wrote my own wrapper for it. https://github.com/Kopernicus/Kopernicus/commit/f82bf6183fb19a81c1ae0ef12747f43d61c8be8a

**Comment by David-JP** [comment]
I am afraid I am still getting continuous pixelFloatD errors, both with the Asc_Height.dds and Asc_Color.dds files. This appears to be leading to the game crashing within 10 to 15 minutes. If I comment out the map calls the game runs continuously without crashing. At this point I don't know if the problem lies with Kopernicus or Asclepius.

[output_log.zip](https://github.com/Kopernicus/Kopernicus/files/244791/output_log.zip)
