### ISSUE TITLE
NullReferenceException at Kopernicus.Components.KopernicusStar.LateUpdate

### ISSUE THREAD

**Issue by Sigma88** [Kopernicus/Kopernicus#245]
I even redownloaded KSP to make sure,

Kopernicus 1.3.1-2 throws this error:

```
NullReferenceException: Object reference not set to an instance of an object
  at Kopernicus.Components.KopernicusStar.LateUpdate () [0x00000] in <filename unknown>:0 
```

nothing installed other than stock ksp 1.3.1 + kopernicus (FGI and MM from kopernicus archive)

logs:
[output_log.txt](https://github.com/Kopernicus/Kopernicus/files/1493461/output_log.txt)
[Kopernicus.zip](https://github.com/Kopernicus/Kopernicus/files/1493462/Kopernicus.zip)

**Comment by Sigma88** [comment]
kopernicus 1.3.1 doesn't throw any errors

**Comment by StollD** [comment]
Yeah, I noticed this too, but I don't have the time to debug it at the moment, so I will just leave this because the code still works, even though it throws

**Comment by Sigma88** [comment]
yeah I just put it here as a reminder

**Comment by Sigma88** [comment]
I don't think 1.3.1-3 has fixed this

**Comment by gschlossnagle** [comment]
I'm suffering the same issue, but for me it loops indefinitely on the exception (appears in a tight loop in the KSP.log forever/till the app is externally terminated).  I can post the log later off my  gaming box.

**Comment by Sigma88** [comment]
this bug is not the cause of that loop, there must be some other stuff going wrong in your install

for a full bug report, go [here](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-121-kopernicus-release-1-november-3/&page=27#comment-2793409) and follow the instructions

**Comment by Sigma88** [comment]
I'm still getting this in Kopernicus 1.3.1-6

**Comment by Sigma88** [comment]
fixed by #269

**Comment by cwongmath** [comment]
I'm still getting the problem with Kopernicus 1.4.3-2. The problem also gets stuck in an endless loop.
![image](https://user-images.githubusercontent.com/32407067/41443473-b61d46b6-7002-11e8-8a8a-eeeba4e06121.png)

**Comment by Sigma88** [comment]
this issue is not the one you are experiencing

if you want help with your problem open a new issue and follow the instructions provided [here](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-143-kopernicus-release-2-may-6/&do=findComment&comment=2793409)
