### ISSUE TITLE
Objects shaded black in the editor when using postSpawnOrbit.

### ISSUE THREAD

**Issue by RJVB09** [Kopernicus/Kopernicus#485]
![screenshot825](https://user-images.githubusercontent.com/49564898/121229052-c8d0c080-c88d-11eb-80ab-5a1da50eb907.png)

-Using most recent version of Kopernicus
-KSP 1.11.2

When using postSpawnOrbit to make my homeworld a moon of a planet, parts, kerbals etc are weirdly shaded black in the editor. 
I know there are multiple other problems with using postSpawnOrbit but this one is possibly the most game hindering, so I'll put it here just in case.

I've attached a config to show what i did (Had to be a .txt so I could upload it)

[033_TemporaHW.txt](https://github.com/Kopernicus/Kopernicus/files/6618488/033_TemporaHW.txt)

**Comment by R-T-B** [comment]
That is odd.  There was a sun tracking bug in a release that I hotfixed just last release.  Maybe this is fixed now too as a result?  If not please update me and I'll look into this.

**Comment by RJVB09** [comment]
> 
> 
> That is odd. There was a sun tracking bug in a release that I hotfixed just last release. Maybe this is fixed now too as a result? If not please update me and I'll look into this.

Nope :/, issue is still there in KSP 1.12 with the latest Kopernicus

**Comment by RJVB09** [comment]
Nvm, this was a problem on my side. The ambient light boost for the editor was somehow at -100% :/
