### ISSUE TITLE
Minor Planets Expansion surface and radar altitude bugs

### ISSUE THREAD

**Issue by ngx-ree** [Kopernicus/Kopernicus#600]
Hello, I noticed two bugs in version 190 with Minor Planets Expansion mod (maybe also with other planets, didn't check them all). Double checked with version 189, which doesn't cause the bugs.

First: some bodies (i.e. Soden, Mracksis, Havous, but also some moons) have surface displayed a little higher than colliders are, so ships look like sunken in sand.

Second: radar altitude on some planets is glitching and most of the time it is set to altitude or even to body radius. By "glitching" I mean sometimes it works correctly for a fracture of second, i.e. during descend. It is observable via kOS, but also has effect on rovers which cannot move, they just spin their wheels. They don't fall through surface though (colliders work).

Provided logs are for both 190 and 189 versions. During testing, following was performed:
1. switch to Soden lander, which "sunk" after loading.
2. switch to Soden rover. This time alt:radar was working and rover could move.
3. switch to Havous rover. Altitude (and alt:radar) were both set to body radius. Rover couldn't move.
4. switch back to Soden rover. This time alt:radar was set to altitude, rover couldn't move.

[_LOGS.ZIP](https://github.com/Kopernicus/Kopernicus/files/13059388/_LOGS.ZIP)

**Comment by R-T-B** [comment]
Thanks for reporting this.  Sounds like a bug introduced by release-190s optimizations, which largely targeted the "sinking terrain on distant bodies" bugfix.  Quick question, if a kerbal gets out of the craft and touches the surface, does it die?

I will look into this for a fix next release.

**Comment by R-T-B** [comment]
I found the bug, it was a pretty dumb optimization I made when under a COVID-induced fever, lol.

Should be fixed with release-191.  Please test.

**Comment by ngx-ree** [comment]
I tested 190 with kerbal, he didn't die, didn't sink either, and he could even walk. It's strange that rover didn't sink as lander did (see attached screenshot), however, radar altitude was still not working and rover couldn't move despite rotating wheels.

![soden](https://github.com/Kopernicus/Kopernicus/assets/45779922/4ebcc819-03fd-4172-a346-bd82316670fc)

Version 191 is working fine, there's no sinking, and radar is working correctly. Thank you!

**Comment by R-T-B** [comment]
Lookin good!  Thanks for reporting so I could catch this!  Closing issue. :)
