### ISSUE TITLE
Inland KSC bug is back

### ISSUE THREAD

**Issue by SuperNoobYT** [Kopernicus/Kopernicus#663]
The old bug where the inland KSC is clumped in a single location is back since release-218
Same affect as this issue previously fixed : https://github.com/Kopernicus/Kopernicus/issues/521

I Tested without kopernicus, with kopernicus-217, with kopernicus-218 and with kopernicus-220 on a fresh install.

**Comment by R-T-B** [comment]
Thanks for letting me know, I will investigate and put a fix in next release.  This shouldn't be hard, the fix was likely just lost in some code reorganization.

**Comment by R-T-B** [comment]
This has been fixed in relase-221.  It should be noted that the way we handle KSC2 is still extremely odd (due to it being "kinda but not quite" a normal PQSCity) and I doubt you can control it much beyond removing or spawing it at stock coordinates.

I'll look into that later.  It's spawning correctly in stock at least now, though.

**Comment by cheba88** [comment]
This issue is still present in release-221 and later versions.

Tested on a stock KSP folder, no mods, uninstalled DLC, then installed release-221.

**Comment by R-T-B** [comment]
Try the latest release?  I swear I tested this recently and it was fixed.  If its not, I'd like to collect some data to determine whats different.

Maybe its the DLCs?  I test with the DLCs present.

**Comment by cheba88** [comment]
I also tested the latest release with clean KSP, and the bug is present there also.

More specifically what happened was that I first came upon this issue with latest Kopernicus + DLC + other mods. I switched to a copy of a clean KSP install folder (including DLC), then uninstalled DLCs through Steam, then installed Kopernicus through CKAN. First 221, then 225, and the bug was present in both versions.

**Comment by R-T-B** [comment]
Interesting.  Can you test with DLCs installed briefly just to see if it works that way?  We may need to adapt the fix for dlc-free users, in that event.

**Comment by R-T-B** [comment]
Interesting.  I swear it was 100% fixed and tested to be so.  You are starting a new game, or loading a save?

My power is out today for electrical work but I'll reopen this and look into it some time tomorrow.

**Comment by cheba88** [comment]
I did actually load a save when testing, I did so out of convenience since I had a flag planted at KSC2 that I could quickly switch to without having to fly all the way there (there are probably ways to teleport but I have never looked into how to do it).

However this particular save hasn't been used with any pre-221 versions of Kopernicus. I know this because this save was created after I had purchased the DLCs and done a clean reinstall of KSP, and according to the purchase history that was on February 13. By that time the latest release of Kopernicus was 223. I have been playing mostly stock since then, during this last weekend I installed Parallax Continued and Kopernicus (latest versions via CKAN) and after that I noticed the issue.

I could try again with a new save tomorrow if needed.

**Comment by R-T-B** [comment]
Hello.  The reason this is such a messy bug is it seems we CAN correct the KSC2 to load correctly, but it becomes uneditable by typical Kopernicus config nodes as a direct consequence of the fix that seems to work.  As such, I have a solution, but it's a bit messy.

I have attached a dev build.  This dev build adds a Kopernicus_Config.cfg parameter, default false, to force the old old KSC2 to load, even though it will become uneditable.  That parameter is named UseOriginalKSC2.  To enable the old KSC2 simply enable this parameter and reload.  The easiest way to acomplish this is to load your game, enter the Kopernicus GUI, check the appropriate option and reload.  Your KSC2 should now be correct.

@cheba88 feel free to test.  This will most likely be in next release later this month:

[Kopernicus-1.12.1-226dev.zip](https://github.com/user-attachments/files/20026413/Kopernicus-1.12.1-226dev.zip)

**Comment by R-T-B** [comment]
This has been as fixed as it can be for a bit now, so closing.
